# Generated by Django 2.2 on 2019-05-01 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configurations', '0002_auto_20190501_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceaction',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceaction',
            name='resource',
            field=models.ForeignKey(db_column='resource', on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.Resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationaction',
            name='action',
            field=models.ForeignKey(db_column='action', on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.ResourceAction'),
        ),
        migrations.AddField(
            model_name='organizationaction',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationaction',
            name='organization',
            field=models.ForeignKey(db_column='organization', on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.Organization'),
        ),
        migrations.AddField(
            model_name='organizationaction',
            name='resource',
            field=models.ForeignKey(db_column='resource', on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.Resource'),
        ),
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.OrganizationCategory'),
        ),
        migrations.AddField(
            model_name='organization',
            name='county',
            field=models.ForeignKey(blank=True, db_column='county', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configurations.County'),
        ),
        migrations.AddField(
            model_name='organization',
            name='sub_county',
            field=models.ForeignKey(blank=True, db_column='sub_county', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configurations.SubCounty'),
        ),
        migrations.AddField(
            model_name='organization',
            name='ward',
            field=models.ForeignKey(blank=True, db_column='ward', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configurations.Ward'),
        ),
    ]
