# Generated by Django 2.2 on 2019-05-03 12:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configurations', '0003_auto_20190503_1537'),
        ('users', '0002_roleaction'),
        ('pos', '0002_auto_20190501_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusparkMatatu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=250, null=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(blank=True, db_column='citizen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Citizen')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='posassignment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 12, 36, 11, 500884, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posassignment',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posassignment',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 5, 3, 12, 36, 16, 165048, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posdevice',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 12, 36, 22, 118761, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posdevice',
            name='is_trashed',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='posdevice',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 5, 3, 12, 36, 36, 721247, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simcard',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 12, 36, 52, 221001, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simcard',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 5, 3, 12, 37, 1, 801838, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VehicleParking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker_number', models.CharField(blank=True, max_length=250, null=True)),
                ('number_plate', models.CharField(max_length=250)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('sticker_collected', models.IntegerField(blank=True, null=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('buspark_matatu', models.ForeignKey(blank=True, db_column='buspark_matatu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pos.BusparkMatatu')),
                ('citizen', models.ForeignKey(blank=True, db_column='citizen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Citizen')),
                ('initiated_by', models.ForeignKey(blank=True, db_column='initiated_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('parking_category', models.ForeignKey(db_column='parking_category', on_delete=django.db.models.deletion.DO_NOTHING, to='configurations.RevenueCategory')),
                ('parking_subcategory', models.ForeignKey(db_column='parking_subcategory', on_delete=django.db.models.deletion.DO_NOTHING, to='configurations.RevenueSubcategory')),
                ('sub_county', models.ForeignKey(blank=True, db_column='sub_county', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configurations.SubCounty')),
                ('validity_period', models.ForeignKey(db_column='validity_period', on_delete=django.db.models.deletion.DO_NOTHING, to='configurations.UnitOfMeasure')),
                ('ward', models.ForeignKey(blank=True, db_column='ward', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configurations.Ward')),
                ('zone', models.ForeignKey(blank=True, db_column='zone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configurations.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='BusparkSacco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='busparkmatatu',
            name='sacco',
            field=models.ForeignKey(blank=True, db_column='sacco', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pos.BusparkSacco'),
        ),
    ]
